spring:
  application:
    name: SliceUploadDemo
  profiles:
    active: dev
minio:
  endpoint: ${oss.endpoint}
  accessKey: ${oss.accessKey}
  secretKey: ${oss.secretKey}
  bucketName: ${oss.bucketName}
  downloadUri: ${oss.downloadUri}
  path: ${oss.path}